"""Export the best DQN checkpoint to src/engine/dqnWeights.json.

Manual step — run after training. The JSON is committed to git; it is not
regenerated by `npm run build`.

Run:  python training/scripts/dqn_export.py
"""

import datetime
import json
import os
import sys

TRAINING_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, TRAINING_DIR)

import torch

from dqn import config
from dqn.qnetwork import QNetwork
from games.tictactoe import TicTacToe

REPO_ROOT = os.path.dirname(TRAINING_DIR)
CHECKPOINT = os.path.join(TRAINING_DIR, "dqn", "checkpoints", "best.pt")
OUT_PATH = os.path.join(REPO_ROOT, "src", "engine", "dqnWeights.json")


def _layer(linear):
    """Serialize a Linear layer: w is row-major [out][in], b is [out]."""
    return {
        "w": linear.weight.detach().tolist(),
        "b": linear.bias.detach().tolist(),
    }


def main():
    game = TicTacToe()
    net = QNetwork(game.input_size, game.action_size)
    net.load_state_dict(torch.load(CHECKPOINT, map_location="cpu"))
    net.eval()

    data = {
        "meta": {
            "inputSize": game.input_size,
            "hiddenSize": config.HIDDEN_SIZE,
            "actionSize": game.action_size,
            "checkpoint": "dqn/checkpoints/best.pt",
            "exportedAt": datetime.date.today().isoformat(),
        },
        "trunk": [_layer(layer) for layer in net.trunk],
        "qHead": _layer(net.q_head),
    }

    with open(OUT_PATH, "w") as f:
        json.dump(data, f)

    shapes = [(len(l["w"]), len(l["w"][0])) for l in data["trunk"]]
    print(f"exported {CHECKPOINT}")
    print(f"      -> {OUT_PATH}")
    print(f"  trunk layers : {shapes}")
    print(f"  q head       : ({len(data['qHead']['w'])}, {len(data['qHead']['w'][0])})")


if __name__ == "__main__":
    main()
