"""Export the DQN difficulty checkpoints to src/engine/dqnWeights*.json.

One file per difficulty — dqnWeightsEasy.json, dqnWeightsMedium.json,
dqnWeightsHard.json. Manual step, run after training. The JSONs are committed
to git; they are not regenerated by `npm run build`.

Run:  python training/scripts/dqn_export.py
"""

import datetime
import json
import os
import sys

TRAINING_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, TRAINING_DIR)

import torch

from dqn import config
from dqn.qnetwork import QNetwork
from games.tictactoe import TicTacToe

REPO_ROOT = os.path.dirname(TRAINING_DIR)
CHECKPOINT_DIR = os.path.join(TRAINING_DIR, "dqn", "checkpoints")
ENGINE_DIR = os.path.join(REPO_ROOT, "src", "engine")


def _layer(linear):
    """Serialize a Linear layer: w is row-major [out][in], b is [out]."""
    return {
        "w": linear.weight.detach().tolist(),
        "b": linear.bias.detach().tolist(),
    }


def export_one(game, difficulty):
    """Load <difficulty>.pt and write src/engine/dqnWeights<Difficulty>.json."""
    checkpoint = os.path.join(CHECKPOINT_DIR, f"{difficulty}.pt")
    net = QNetwork(game.input_size, game.action_size)
    net.load_state_dict(torch.load(checkpoint, map_location="cpu"))
    net.eval()

    data = {
        "meta": {
            "inputSize": game.input_size,
            "hiddenSize": config.HIDDEN_SIZE,
            "actionSize": game.action_size,
            "difficulty": difficulty,
            "checkpoint": f"dqn/checkpoints/{difficulty}.pt",
            "exportedAt": datetime.date.today().isoformat(),
        },
        "trunk": [_layer(layer) for layer in net.trunk],
        "qHead": _layer(net.q_head),
    }

    out_path = os.path.join(ENGINE_DIR, f"dqnWeights{difficulty.capitalize()}.json")
    with open(out_path, "w") as f:
        json.dump(data, f)
    return out_path


def main():
    game = TicTacToe()
    for difficulty in config.DIFFICULTY_TARGETS:
        out_path = export_one(game, difficulty)
        print(f"exported {difficulty:7s} -> {out_path}")


if __name__ == "__main__":
    main()
