"""Export the best checkpoint to src/engine/weights.json for the web app.

This is a manual step — run it after training. The JSON is committed to git;
it is deliberately NOT regenerated by `npm run build`.

Run:  python training/scripts/export_weights.py
"""

import datetime
import json
import os
import sys

TRAINING_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, TRAINING_DIR)

import torch

import config
from alphazero.network import PolicyValueNet
from games.tictactoe import TicTacToe

REPO_ROOT = os.path.dirname(TRAINING_DIR)
CHECKPOINT = os.path.join(TRAINING_DIR, "checkpoints", "best.pt")
OUT_PATH = os.path.join(REPO_ROOT, "src", "engine", "weights.json")


def _layer(linear):
    """Serialize a Linear layer: w is row-major [out][in], b is [out]."""
    return {
        "w": linear.weight.detach().tolist(),
        "b": linear.bias.detach().tolist(),
    }


def main():
    game = TicTacToe()
    net = PolicyValueNet(game.input_size, game.action_size)
    net.load_state_dict(torch.load(CHECKPOINT, map_location="cpu"))
    net.eval()

    data = {
        "meta": {
            "inputSize": game.input_size,
            "hiddenSize": config.HIDDEN_SIZE,
            "actionSize": game.action_size,
            "cPuct": config.C_PUCT,
            "numSimulations": config.PLAY_SIMULATIONS,
            "checkpoint": "checkpoints/best.pt",
            "exportedAt": datetime.date.today().isoformat(),
        },
        "trunk": [_layer(layer) for layer in net.trunk],
        "policyHead": _layer(net.policy_head),
        "valueHead": _layer(net.value_head),
    }

    with open(OUT_PATH, "w") as f:
        json.dump(data, f)

    shapes = [(len(l["w"]), len(l["w"][0])) for l in data["trunk"]]
    print(f"exported {CHECKPOINT}")
    print(f"      -> {OUT_PATH}")
    print(f"  trunk layers : {shapes}")
    print(f"  policy head  : ({len(data['policyHead']['w'])}, "
          f"{len(data['policyHead']['w'][0])})")
    print(f"  value head   : ({len(data['valueHead']['w'])}, "
          f"{len(data['valueHead']['w'][0])})")


if __name__ == "__main__":
    main()
